### ISSUE TITLE
Doesn't build with latest Qt 5.14

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-control-center#275]
```
[ 31%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/window/modules/power/generalwidget.cpp.o
/build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp: In member function ‘virtual void dccV20::MainWindow::keyPressEvent(QKeyEvent*)’:
/build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:593:18: error: invalid use of incomplete type ‘class QKeyEvent’
  593 |     switch (event->key()) {
      |                  ^~
In file included from /usr/include/qt/QtWidgets/qabstractspinbox.h:44,
                 from /usr/include/qt/QtWidgets/qstyleoption.h:47,
                 from /usr/include/qt/QtWidgets/QStyleOption:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleoption.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DFontSizeManager:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleditemdelegate.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DStyledItemDelegate:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dlistview.h:24,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DListView:1,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/customsettingdialog.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/displaymodule.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:32:
/usr/include/qt/QtWidgets/qwidget.h:75:7: note: forward declaration of ‘class QKeyEvent’
   75 | class QKeyEvent;
      |       ^~~~~~~~~
/build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp: In member function ‘virtual void dccV20::MainWindow::resizeEvent(QResizeEvent*)’:
/build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:624:26: error: invalid use of incomplete type ‘class QResizeEvent’
  624 |     auto dstWidth = event->size().width();
      |                          ^~
In file included from /usr/include/qt/QtWidgets/qabstractspinbox.h:44,
                 from /usr/include/qt/QtWidgets/qstyleoption.h:47,
                 from /usr/include/qt/QtWidgets/QStyleOption:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleoption.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DFontSizeManager:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleditemdelegate.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DStyledItemDelegate:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dlistview.h:24,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DListView:1,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/customsettingdialog.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/displaymodule.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:32:
/usr/include/qt/QtWidgets/qwidget.h:79:7: note: forward declaration of ‘class QResizeEvent’
   79 | class QResizeEvent;
      |       ^~~~~~~~~~~~
/build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:655:40: error: invalid use of incomplete type ‘class QResizeEvent’
  655 |         m_topWidget->setFixedSize(event->size());
      |                                        ^~
In file included from /usr/include/qt/QtWidgets/qabstractspinbox.h:44,
                 from /usr/include/qt/QtWidgets/qstyleoption.h:47,
                 from /usr/include/qt/QtWidgets/QStyleOption:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleoption.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DFontSizeManager:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleditemdelegate.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DStyledItemDelegate:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dlistview.h:24,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DListView:1,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/customsettingdialog.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/displaymodule.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:32:
/usr/include/qt/QtWidgets/qwidget.h:79:7: note: forward declaration of ‘class QResizeEvent’
   79 | class QResizeEvent;
      |       ^~~~~~~~~~~~
[ 31%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/window/modules/power/useelectricwidget.cpp.o
/build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp: In member function ‘virtual void dccV20::FourthColWidget::mousePressEvent(QMouseEvent*)’:
/build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:1082:47: error: invalid use of incomplete type ‘class QMouseEvent’
 1082 |     if (m_curWidget->geometry().contains(event->pos()))
      |                                               ^~
In file included from /usr/include/qt/QtWidgets/qabstractspinbox.h:44,
                 from /usr/include/qt/QtWidgets/qstyleoption.h:47,
                 from /usr/include/qt/QtWidgets/QStyleOption:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleoption.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DFontSizeManager:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dstyleditemdelegate.h:27,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DStyledItemDelegate:1,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/dlistview.h:24,
                 from /usr/include/libdtk-5.2.0/DCore/../DWidget/DListView:1,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/customsettingdialog.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/modules/display/displaymodule.h:27,
                 from /build/deepin-control-center/src/dde-control-center-5.1.0.0/src/frame/window/mainwindow.cpp:32:
/usr/include/qt/QtWidgets/qwidget.h:72:7: note: forward declaration of ‘class QMouseEvent’
   72 | class QMouseEvent;
      |       ^~~~~~~~~~~
[ 31%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/window/modules/power/usebatterywidget.cpp.o
[ 31%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/window/modules/sound/soundwidget.cpp.o
[ 32%] Building CXX object src/frame/CMakeFiles/dde-control-center.dir/window/modules/sound/soundmodule.cpp.o
make[2]: *** [src/frame/CMakeFiles/dde-control-center.dir/build.make:1884: src/frame/CMakeFiles/dde-control-center.dir/window/mainwindow.cpp.o] Error 1
```

**Comment by justforlxz** [comment]
```
diff --git a/src/frame/updatenotifier.cpp b/src/frame/updatenotifier.cpp
index d30178285..b3c2a9400 100644
--- a/src/frame/updatenotifier.cpp
+++ b/src/frame/updatenotifier.cpp
@@ -186,8 +186,8 @@ bool UpdateNotifier::comparePkgLists(QStringList val1, QStringList val2)
 {
     if (val1.length() != val2.length()) return false;
 
-    qSort(val1.begin(), val1.end());
-    qSort(val2.begin(), val2.end());
+    std::sort(val1.begin(), val1.end());
+    std::sort(val2.begin(), val2.end());
 
     return val1 == val2;
 }
diff --git a/src/frame/window/mainwindow.cpp b/src/frame/window/mainwindow.cpp
index a073a8240..2c12d49d0 100644
--- a/src/frame/window/mainwindow.cpp
+++ b/src/frame/window/mainwindow.cpp
@@ -59,6 +59,8 @@
 #include <QLinearGradient>
 #include <QGSettings>
 #include <QScroller>
+#include <QMouseEvent>
+#include <QResizeEvent>
 
 using namespace DCC_NAMESPACE;
 using namespace DCC_NAMESPACE::search;
diff --git a/src/frame/window/modules/accounts/avatarlistwidget.cpp b/src/frame/window/modules/accounts/avatarlistwidget.cpp
index 16bd33ee3..d690ae876 100644
--- a/src/frame/window/modules/accounts/avatarlistwidget.cpp
+++ b/src/frame/window/modules/accounts/avatarlistwidget.cpp
@@ -200,7 +200,7 @@ void AvatarListWidget::addItemFromDefaultDir()
     QFileInfoList list = dir.entryInfoList();
 
     //根据文件名进行排序
-    qSort(list.begin(), list.end(), [&](const QFileInfo &fileinfo1, const QFileInfo &fileinfo2) {
+    std::sort(list.begin(), list.end(), [&](const QFileInfo &fileinfo1, const QFileInfo &fileinfo2) {
         return fileinfo1.baseName() < fileinfo2.baseName();
     });
 
diff --git a/src/frame/window/search/searchwidget.cpp b/src/frame/window/search/searchwidget.cpp
index 00f5b8830..33763ebb9 100755
--- a/src/frame/window/search/searchwidget.cpp
+++ b/src/frame/window/search/searchwidget.cpp
@@ -31,6 +31,7 @@
 #include <QXmlStreamReader>
 #include <QCompleter>
 #include <QRegularExpression>
+#include <QKeyEvent>
 
 using namespace DCC_NAMESPACE;
 using namespace DCC_NAMESPACE::search;
```
